--- @diagnostic disable
--- @class Jack
--- @field config JackConfig
--- @field palette JackPalette
local Jack = {}

--- @alias Contrast "hard" | "sorf" | ""
--- @alias Theme "tiger" |  ""
--- @class HighlightDefinition
--- @fg string?
--- @bg string?
--- @bold boolean?
--- @underline boolean?

--- @class JackConfig
--- @field overwrites table<string, HighlightDefinition>?
--- @field palette_overwrites table<string, string>?
--- @field contrast Contrast?
--- @field terminal_colors boolean?
--- @field invert_signs boolean?
--- @field bold boolean?
--- @field transparent_mode boolean?
--- @field undercurl boolean?
--- @field dim_inactive boolean?
--- @field invert_tabline boolean?
--- @field invert_selection boolean?
--- @field underline boolean?
--- @field inverse boolean?
--- @field italic_comments boolean?
--- @field italic_operators boolean?
--- @field italic_strings boolean?
--- @field italic_emphasis boolean?
--- @field italic_folds boolean?
Jack.config = {
	terminal_colors = true,
	undercurl = true,
	underline = true,
	bold = true,
	italic_strings = true,
	italic_emphasis = true,
	italic_comments = true,
	italic_operators = false,
	italic_folds = true,
	strikethrough = true,
	invert_selection = false,
	invert_signs = false,
	invert_tabline = false,
	invert_intend_guides = false,
	inverse = true,
	contrast = "",
	palette_overwrites = {},
	overwrites = {},
	dim_inactive = false,
	transparent_mode = false,
}

--[[ colors list
	dark0 = "#181808",
	dark1 = "#3c3800",
	dark0_hard = "#1d2021",
	dark0_soft = "#32302f",
	-- bright_red = "#fb4934",
	-- light1 = "#ebdbb2",
	-- bright_yellow = "#fabd2f",
	-- bright_yellow = "#FF8C00",
	-- bright_yellow = "#FFA500",
	-- bright_yellow = "#fe8010",
	-- bright_aqua = "#8ec040",

	bright_red = "#fb4934",
]]
--- @class JackPalette
Jack.palette = {
	dark0 = "#161616",
	dark1 = "#302624",
	dark2 = "#504644",
	dark3 = "#665c50",
	dark4 = "#5c4f32",

	light0 = "#fbf1a7",
	light1 = "#f8bb44",
	light2 = "#d5c440",
	light3 = "#bdae93",
	light4 = "#a89984",
	gray = "#928344",

	red = "#eb4034",
	-- green = "#98971a",
	green = "#80801a",
	yellow = "#fabd42",
	light_orange = "#ec8832",
	orange = "#dd8020",
	dark_orange = "#eb7b44",
	aqua = "#8ec060",
	dark_aqua = "#eb7b44",

	-- default gruvbox colors for compatibility

	dark0_hard = "#1d2021",
	dark0_soft = "#32302f",
	light0_hard = "#f9f5d7",
	light0_soft = "#f2e5bc",
	neutral_red = "#cc241d",
	neutral_green = "#98971a",
	neutral_yellow = "#d79921",
	neutral_blue = "#458588",
	neutral_purple = "#b16286",
	neutral_aqua = "#689d6a",
	neutral_orange = "#d65d0e",
	faded_red = "#9d0006",
	faded_green = "#79740e",
	faded_yellow = "#b57614",
	faded_blue = "#076678",
	faded_purple = "#8f3f71",
	faded_aqua = "#427b58",
	faded_orange = "#af3a03",
	dark_red_hard = "#792329",
	dark_red = "#722529",
	dark_red_soft = "#7b2c2f",
	light_red_hard = "#fc9690",
	light_red = "#fc9487",
	light_red_soft = "#f78b7f",
	dark_green_hard = "#5a633a",
	dark_green_hard = "#5a633a",
	dark_green = "#62693e",
	dark_green_soft = "#686d43",
	light_green_hard = "#d3d6a5",
	light_green = "#d5d39b",
	light_green_soft = "#cecb94",
	dark_aqua_hard = "#3e4934",
	dark_aqua_soft = "#525742",
	light_aqua_hard = "#e6e9c1",
	light_aqua = "#e8e5b5",
	light_aqua_soft = "#e1dbac",
}

-- Theme: "tiger"

-- @class Tiger
-- @field get_colors function()
-- @field get_groups function()
local Tiger = {}

Tiger.get_colors = function()
	local p = Jack.palette
	-- DEV: set default missing value to white
	setmetatable(p, {
		__index = function()
			return "#ffffff"
		end,
	})
	local config = Jack.config

	for color, hex in pairs(config.palette_overwrites) do
		p[color] = hex
	end
	local bg = vim.o.background
	local contrast = config.contrast

	local color_groups = {
		dark = {
			bg0 = p.dark0,
			bg1 = p.dark1,
			bg2 = p.dark2,
			bg3 = p.dark3,
			bg4 = p.dark4,
			fg0 = p.light0,
			fg1 = p.light1,
			fg2 = p.light2,
			fg3 = p.light3,
			fg4 = p.light4,
			gray = p.gray,

			green = p.green,
			yellow = p.yellow,
			aqua = p.aqua,
			red = p.red,
			light_orange = p.light_orange,
			orange = p.orange,
			dark_orange = p.dark_orange,

			-- using default gruvbox colors
			neutral_red = p.neutral_red,
			neutral_green = p.neutral_green,
			neutral_yellow = p.neutral_yellow,
			neutral_blue = p.neutral_blue,
			neutral_purple = p.neutral_purple,
			neutral_aqua = p.neutral_aqua,
			dark_red = p.dark_red,
			dark_green = p.dark_green,
			dark_aqua = p.dark_aqua,
		},
		light = {
			bg0 = p.light0,
			bg1 = p.light1,
			bg2 = p.light2,
			bg3 = p.light3,
			bg4 = p.light4,
			fg0 = p.dark0,
			fg1 = p.dark1,
			fg2 = p.dark2,
			fg3 = p.dark3,
			fg4 = p.dark4,
			gray = p.gray,

			green = p.green,
			yellow = p.yellow,
			aqua = p.aqua,
			red = p.red,
			light_orange = p.light_orange,
			orange = p.orange,
			dark_orange = p.dark_orange,

			-- using default gruvbox colors
			neutral_red = p.neutral_red,
			neutral_green = p.neutral_green,
			neutral_yellow = p.neutral_yellow,
			neutral_blue = p.neutral_blue,
			neutral_purple = p.neutral_purple,
			neutral_aqua = p.neutral_aqua,
			dark_red = p.dark_red,
			dark_green = p.dark_green,
			dark_aqua = p.dark_aqua,
		},
	}
	-- TODO: contrast manipulation
	--if contrast ~= nil and contrast ~= "" then
	--[[ color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
		color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
		color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
		color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast] ]]
	-- end
	return color_groups[bg]
end

Tiger.get_groups = function()
	local colors = Tiger.get_colors()
	local config = Jack.config

	if config.terminal_colors then
	end

	local groups = {
		JackFg0 = { fg = colors.fg0 },
		JackFg1 = { fg = colors.fg1 },
		JackFg2 = { fg = colors.fg2 },
		JackFg3 = { fg = colors.fg3 },
		JackFg4 = { fg = colors.fg4 },
		JackGray = { fg = colors.gray },
		JackBg0 = { fg = colors.bg0 },
		JackBg1 = { fg = colors.bg1 },
		JackBg2 = { fg = colors.bg2 },
		JackBg3 = { fg = colors.bg3 },
		JackBg4 = { fg = colors.bg4 },
		JackRed = { fg = colors.red },
		JackRedBold = { fg = colors.red, bold = config.bold },
		JackGreen = { fg = colors.green },
		JackGreenBold = { fg = colors.green, bold = config.bold },
		JackYellow = { fg = colors.yellow },
		JackYellowBold = { fg = colors.yellow, bold = config.bold },
		JackBlue = { fg = colors.light_orange },
		JackBlueBold = { fg = colors.light_orange, bold = config.bold },
		JackDarkOrange = { fg = colors.dark_orange },
		JackDarkOrangeBold = { fg = colors.dark_orange, bold = config.bold },
		JackAqua = { fg = colors.aqua },
		JackAquaBold = { fg = colors.aqua, bold = config.bold },
		JackOrange = { fg = colors.orange },
		JackOrangeBold = { fg = colors.orange, bold = config.bold },
		JackRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
			or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
		JackGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
			or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
		JackYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
			or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
		JackBlueSign = config.transparent_mode and { fg = colors.light_orange, reverse = config.invert_signs }
			or { fg = colors.light_orange, bg = colors.bg1, reverse = config.invert_signs },
		JackDarkOrangeSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
			or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
		JackAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
			or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
		JackOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
			or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
		JackRedUnderline = { undercurl = config.undercurl, sp = colors.red },
		JackGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
		JackYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
		JackBlueUnderline = { undercurl = config.undercurl, sp = colors.light_orange },
		JackDarkOrangeUnderline = { undercurl = config.undercurl, sp = colors.purple },
		JackAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
		JackOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
		Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
		NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
		NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
		CursorLine = { bg = colors.bg1 },
		CursorColumn = { link = "CursorLine" },
		TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
		TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
		TabLine = { link = "TabLineFill" },
		MatchParen = { bg = colors.bg3, bold = config.bold },
		ColorColumn = { bg = colors.bg1 },
		Conceal = { fg = colors.light_orange },
		CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
		NonText = { link = "JackBg2" },
		SpecialKey = { link = "JackFg4" },
		Visual = { bg = colors.bg2, reverse = config.invert_selection },
		VisualNOS = { link = "Visual" },
		Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
		IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
		CurSearch = { link = "IncSearch" },
		QuickFixLine = { link = "JackDarkOrange" },
		Underlined = { fg = colors.light_orange, underline = config.underline },
		StatusLine = { fg = colors.fg1, bg = colors.bg2 },
		StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
		WinBar = { fg = colors.fg4, bg = colors.bg0 },
		WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
		WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil }
			or { fg = colors.bg3, bg = colors.bg0 },
		WildMenu = { fg = colors.light_orange, bg = colors.bg2, bold = config.bold },
		Directory = { link = "JackGreenBold" },
		Title = { link = "JackGreenBold" },
		ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
		MoreMsg = { link = "JackYellowBold" },
		ModeMsg = { link = "JackYellowBold" },
		Question = { link = "JackOrangeBold" },
		WarningMsg = { link = "JackRedBold" },
		LineNr = { fg = colors.bg4 },
		SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
		Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic_folds },
		FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil }
			or { fg = colors.gray, bg = colors.bg1 },
		Cursor = { reverse = config.inverse },
		vCursor = { link = "Cursor" },
		iCursor = { link = "Cursor" },
		lCursor = { link = "Cursor" },
		Special = { link = "JackOrange" },
		Comment = { fg = colors.gray, italic = config.italic_comments },
		Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic_comments },
		Done = { fg = colors.orange, bold = config.bold, italic = config.italic_comments },
		Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
		Statement = { link = "JackRed" },
		Conditional = { link = "JackRed" },
		Repeat = { link = "JackRed" },
		Label = { link = "JackRed" },
		Exception = { link = "JackRed" },
		Operator = { fg = colors.orange, italic = config.italic_operators },
		Keyword = { link = "JackRed" },
		Identifier = { link = "JackBlue" },
		Function = { link = "JackGreenBold" },
		PreProc = { link = "JackAqua" },
		Include = { link = "JackAqua" },
		Define = { link = "JackAqua" },
		Macro = { link = "JackAqua" },
		PreCondit = { link = "JackAqua" },
		Constant = { link = "JackDarkOrange" },
		Character = { link = "JackDarkOrange" },
		String = { fg = colors.green, italic = config.italic_strings },
		Boolean = { link = "JackDarkOrange" },
		Number = { link = "JackDarkOrange" },
		Float = { link = "JackDarkOrange" },
		Type = { link = "JackYellow" },
		StorageClass = { link = "JackOrange" },
		Structure = { link = "JackAqua" },
		Typedef = { link = "JackYellow" },
		Pmenu = { fg = colors.fg1, bg = colors.bg2 },
		PmenuSel = { fg = colors.bg2, bg = colors.light_orange, bold = config.bold },
		PmenuSbar = { bg = colors.bg2 },
		PmenuThumb = { bg = colors.bg4 },
		DiffDelete = { bg = colors.dark_red },
		DiffAdd = { bg = colors.dark_green },
		DiffChange = { bg = colors.dark_aqua },
		DiffText = { bg = colors.yellow, fg = colors.bg0 },
		SpellCap = { link = "JackBlueUnderline" },
		SpellBad = { link = "JackRedUnderline" },
		SpellLocal = { link = "JackAquaUnderline" },
		SpellRare = { link = "JackDarkOrangeUnderline" },
		lightspace = { fg = colors.bg2 },
		Delimiter = { link = "JackOrange" },
		EndOfBuffer = { link = "NonText" },
		DiagnosticError = { link = "JackRed" },
		DiagnosticSignError = { link = "JackRedSign" },
		DiagnosticUnderlineError = { link = "JackRedUnderline" },
		DiagnosticWarn = { link = "JackYellow" },
		DiagnosticSignWarn = { link = "JackYellowSign" },
		DiagnosticUnderlineWarn = { link = "JackYellowUnderline" },
		DiagnosticInfo = { link = "JackBlue" },
		DiagnosticSignInfo = { link = "JackBlueSign" },
		DiagnosticUnderlineInfo = { link = "JackBlueUnderline" },
		DiagnosticHint = { link = "JackAqua" },
		DiagnosticSignHint = { link = "JackAquaSign" },
		DiagnosticUnderlineHint = { link = "JackAquaUnderline" },
		DiagnosticFloatingError = { link = "JackRed" },
		DiagnosticFloatingWarn = { link = "JackOrange" },
		DiagnosticFloatingInfo = { link = "JackBlue" },
		DiagnosticFloatingHint = { link = "JackAqua" },
		DiagnosticVirtualTextError = { link = "JackRed" },
		DiagnosticVirtualTextWarn = { link = "JackYellow" },
		DiagnosticVirtualTextInfo = { link = "JackBlue" },
		DiagnosticVirtualTextHint = { link = "JackAqua" },
		DiagnosticOk = { link = "JackGreenSign" },
		LspReferenceRead = { link = "JackYellowBold" },
		LspReferenceTarget = { link = "Visual" },
		LspReferenceText = { link = "JackYellowBold" },
		LspReferenceWrite = { link = "JackOrangeBold" },
		LspCodeLens = { link = "JackGray" },
		LspSignatureActiveParameter = { link = "Search" },
		gitcommitSelectedFile = { link = "JackGreen" },
		gitcommitDiscardedFile = { link = "JackRed" },
		GitSignsAdd = { link = "JackGreen" },
		GitSignsChange = { link = "JackOrange" },
		GitSignsDelete = { link = "JackRed" },
		NvimTreeSymlink = { fg = colors.neutral_aqua },
		NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
		NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
		NvimTreeFileIcon = { fg = colors.light2 },
		NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
		NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
		NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
		NvimTreeImageFile = { fg = colors.neutral_purple },
		NvimTreeIndentMarker = { fg = colors.dark3 },
		NvimTreeGitDirty = { fg = colors.neutral_yellow },
		NvimTreeGitStaged = { fg = colors.neutral_yellow },
		NvimTreeGitMerge = { fg = colors.neutral_purple },
		NvimTreeGitRenamed = { fg = colors.neutral_purple },
		NvimTreeGitNew = { fg = colors.neutral_yellow },
		NvimTreeGitDeleted = { fg = colors.neutral_red },
		NvimTreeWindowPicker = { bg = colors.aqua },
		debugPC = { link = "DiffAdd" },
		debugBreakpoint = { link = "JackRedSign" },
		StartifyBracket = { link = "JackFg3" },
		StartifyFile = { link = "JackFg1" },
		StartifyNumber = { link = "JackBlue" },
		StartifyPath = { link = "JackGray" },
		StartifySlash = { link = "JackGray" },
		StartifySection = { link = "JackYellow" },
		StartifySpecial = { link = "JackBg2" },
		StartifyHeader = { link = "JackOrange" },
		StartifyFooter = { link = "JackBg2" },
		StartifyVar = { link = "StartifyPath" },
		StartifySelect = { link = "Title" },
		DirvishPathTail = { link = "JackAqua" },
		DirvishArg = { link = "JackYellow" },
		netrwDir = { link = "JackAqua" },
		netrwClassify = { link = "JackAqua" },
		netrwLink = { link = "JackGray" },
		netrwSymLink = { link = "JackFg1" },
		netrwExe = { link = "JackYellow" },
		netrwComment = { link = "JackGray" },
		netrwList = { link = "JackBlue" },
		netrwHelpCmd = { link = "JackAqua" },
		netrwCmdSep = { link = "JackFg3" },
		netrwVersion = { link = "JackGreen" },
		NERDTreeDir = { link = "JackAqua" },
		NERDTreeDirSlash = { link = "JackAqua" },
		NERDTreeOpenable = { link = "JackOrange" },
		NERDTreeClosable = { link = "JackOrange" },
		NERDTreeFile = { link = "JackFg1" },
		NERDTreeExecFile = { link = "JackYellow" },
		NERDTreeUp = { link = "JackGray" },
		NERDTreeCWD = { link = "JackGreen" },
		NERDTreeHelp = { link = "JackFg1" },
		NERDTreeToggleOn = { link = "JackGreen" },
		NERDTreeToggleOff = { link = "JackRed" },
		CocErrorSign = { link = "JackRedSign" },
		CocWarningSign = { link = "JackOrangeSign" },
		CocInfoSign = { link = "JackBlueSign" },
		CocHintSign = { link = "JackAquaSign" },
		CocErrorFloat = { link = "JackRed" },
		CocWarningFloat = { link = "JackOrange" },
		CocInfoFloat = { link = "JackBlue" },
		CocHintFloat = { link = "JackAqua" },
		CocDiagnosticsError = { link = "JackRed" },
		CocDiagnosticsWarning = { link = "JackOrange" },
		CocDiagnosticsInfo = { link = "JackBlue" },
		CocDiagnosticsHint = { link = "JackAqua" },
		CocSearch = { link = "JackBlue" },
		CocSelectedText = { link = "JackRed" },
		CocMenuSel = { link = "PmenuSel" },
		CocCodeLens = { link = "JackGray" },
		CocErrorHighlight = { link = "JackRedUnderline" },
		CocWarningHighlight = { link = "JackOrangeUnderline" },
		CocInfoHighlight = { link = "JackBlueUnderline" },
		CocHintHighlight = { link = "JackAquaUnderline" },
		TelescopeNormal = { link = "JackFg1" },
		TelescopeSelection = { link = "JackOrangeBold" },
		TelescopeSelectionCaret = { link = "JackRed" },
		TelescopeMultiSelection = { link = "JackGray" },
		TelescopeBorder = { link = "TelescopeNormal" },
		TelescopePromptBorder = { link = "TelescopeNormal" },
		TelescopeResultsBorder = { link = "TelescopeNormal" },
		TelescopePreviewBorder = { link = "TelescopeNormal" },
		TelescopeMatching = { link = "JackBlue" },
		TelescopePromptPrefix = { link = "JackRed" },
		TelescopePrompt = { link = "TelescopeNormal" },
		CmpItemAbbr = { link = "JackFg0" },
		CmpItemAbbrDeprecated = { link = "JackFg1" },
		CmpItemAbbrMatch = { link = "JackBlueBold" },
		CmpItemAbbrMatchFuzzy = { link = "JackBlueUnderline" },
		CmpItemMenu = { link = "JackGray" },
		CmpItemKindText = { link = "JackOrange" },
		CmpItemKindVariable = { link = "JackOrange" },
		CmpItemKindMethod = { link = "JackBlue" },
		CmpItemKindFunction = { link = "JackBlue" },
		CmpItemKindConstructor = { link = "JackYellow" },
		CmpItemKindUnit = { link = "JackBlue" },
		CmpItemKindField = { link = "JackBlue" },
		CmpItemKindClass = { link = "JackYellow" },
		CmpItemKindInterface = { link = "JackYellow" },
		CmpItemKindModule = { link = "JackBlue" },
		CmpItemKindProperty = { link = "JackBlue" },
		CmpItemKindValue = { link = "JackOrange" },
		CmpItemKindEnum = { link = "JackYellow" },
		CmpItemKindOperator = { link = "JackYellow" },
		CmpItemKindKeyword = { link = "JackDarkOrange" },
		CmpItemKindEvent = { link = "JackDarkOrange" },
		CmpItemKindReference = { link = "JackDarkOrange" },
		CmpItemKindColor = { link = "JackDarkOrange" },
		CmpItemKindSnippet = { link = "JackGreen" },
		CmpItemKindFile = { link = "JackBlue" },
		CmpItemKindFolder = { link = "JackBlue" },
		CmpItemKindEnumMember = { link = "JackAqua" },
		CmpItemKindConstant = { link = "JackOrange" },
		CmpItemKindStruct = { link = "JackYellow" },
		CmpItemKindTypeParameter = { link = "JackYellow" },
		BlinkCmpLabel = { link = "JackFg0" },
		BlinkCmpLabelDeprecated = { link = "JackFg1" },
		BlinkCmpLabelMatch = { link = "JackBlueBold" },
		BlinkCmpLabelDetail = { link = "JackGray" },
		BlinkCmpLabelDescription = { link = "JackGray" },
		BlinkCmpKindText = { link = "JackOrange" },
		BlinkCmpKindVariable = { link = "JackOrange" },
		BlinkCmpKindMethod = { link = "JackBlue" },
		BlinkCmpKindFunction = { link = "JackBlue" },
		BlinkCmpKindConstructor = { link = "JackYellow" },
		BlinkCmpKindUnit = { link = "JackBlue" },
		BlinkCmpKindField = { link = "JackBlue" },
		BlinkCmpKindClass = { link = "JackYellow" },
		BlinkCmpKindInterface = { link = "JackYellow" },
		BlinkCmpKindModule = { link = "JackBlue" },
		BlinkCmpKindProperty = { link = "JackBlue" },
		BlinkCmpKindValue = { link = "JackOrange" },
		BlinkCmpKindEnum = { link = "JackYellow" },
		BlinkCmpKindOperator = { link = "JackYellow" },
		BlinkCmpKindKeyword = { link = "JackDarkOrange" },
		BlinkCmpKindEvent = { link = "JackDarkOrange" },
		BlinkCmpKindReference = { link = "JackDarkOrange" },
		BlinkCmpKindColor = { link = "JackDarkOrange" },
		BlinkCmpKindSnippet = { link = "JackGreen" },
		BlinkCmpKindFile = { link = "JackBlue" },
		BlinkCmpKindFolder = { link = "JackBlue" },
		BlinkCmpKindEnumMember = { link = "JackAqua" },
		BlinkCmpKindConstant = { link = "JackOrange" },
		BlinkCmpKindStruct = { link = "JackYellow" },
		BlinkCmpKindTypeParameter = { link = "JackYellow" },
		BlinkCmpSource = { link = "JackGray" },
		BlinkCmpGhostText = { link = "JackBg4" },
		diffAdded = { link = "DiffAdd" },
		diffRemoved = { link = "DiffDelete" },
		diffChanged = { link = "DiffChange" },
		diffFile = { link = "JackOrange" },
		diffNewFile = { link = "JackYellow" },
		diffOldFile = { link = "JackOrange" },
		diffLine = { link = "JackBlue" },
		diffIndexLine = { link = "diffChanged" },
		NavicIconsFile = { link = "JackBlue" },
		NavicIconsModule = { link = "JackOrange" },
		NavicIconsNamespace = { link = "JackBlue" },
		NavicIconsPackage = { link = "JackAqua" },
		NavicIconsClass = { link = "JackYellow" },
		NavicIconsMethod = { link = "JackBlue" },
		NavicIconsProperty = { link = "JackAqua" },
		NavicIconsField = { link = "JackDarkOrange" },
		NavicIconsConstructor = { link = "JackBlue" },
		NavicIconsEnum = { link = "JackDarkOrange" },
		NavicIconsInterface = { link = "JackGreen" },
		NavicIconsFunction = { link = "JackBlue" },
		NavicIconsVariable = { link = "JackDarkOrange" },
		NavicIconsConstant = { link = "JackOrange" },
		NavicIconsString = { link = "JackGreen" },
		NavicIconsNumber = { link = "JackOrange" },
		NavicIconsBoolean = { link = "JackOrange" },
		NavicIconsArray = { link = "JackOrange" },
		NavicIconsObject = { link = "JackOrange" },
		NavicIconsKey = { link = "JackAqua" },
		NavicIconsNull = { link = "JackOrange" },
		NavicIconsEnumMember = { link = "JackYellow" },
		NavicIconsStruct = { link = "JackDarkOrange" },
		NavicIconsEvent = { link = "JackYellow" },
		NavicIconsOperator = { link = "JackRed" },
		NavicIconsTypeParameter = { link = "JackRed" },
		NavicText = { link = "Jacklight" },
		NavicSeparator = { link = "Jacklight" },
		htmlTag = { link = "JackAquaBold" },
		htmlEndTag = { link = "JackAquaBold" },
		htmlTagName = { link = "JackBlue" },
		htmlArg = { link = "JackOrange" },
		htmlTagN = { link = "JackFg1" },
		htmlSpecialTagName = { link = "JackBlue" },
		htmlLink = { fg = colors.fg4, underline = config.underline },
		htmlSpecialChar = { link = "JackRed" },
		htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
		htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
		htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
		htmlBoldUnderlineItalic = {
			fg = colors.fg0,
			bg = colors.bg0,
			bold = config.bold,
			italic = true,
			underline = config.underline,
		},
		htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
		htmlUnderlineItalic = {
			fg = colors.fg0,
			bg = colors.bg0,
			italic = true,
			underline = config.underline,
		},
		htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
		xmlTag = { link = "JackAquaBold" },
		xmlEndTag = { link = "JackAquaBold" },
		xmlTagName = { link = "JackBlue" },
		xmlEqual = { link = "JackBlue" },
		docbkKeyword = { link = "JackAquaBold" },
		xmlDocTypeDecl = { link = "JackGray" },
		xmlDocTypeKeyword = { link = "JackDarkOrange" },
		xmlCdataStart = { link = "JackGray" },
		xmlCdataCdata = { link = "JackDarkOrange" },
		dtdFunction = { link = "JackGray" },
		dtdTagName = { link = "JackDarkOrange" },
		xmlAttrib = { link = "JackOrange" },
		xmlProcessingDelim = { link = "JackGray" },
		dtdParamEntityPunct = { link = "JackGray" },
		dtdParamEntityDPunct = { link = "JackGray" },
		xmlAttribPunct = { link = "JackGray" },
		xmlEntity = { link = "JackRed" },
		xmlEntityPunct = { link = "JackRed" },
		clojureKeyword = { link = "JackBlue" },
		clojureCond = { link = "JackOrange" },
		clojureSpecial = { link = "JackOrange" },
		clojureDefine = { link = "JackOrange" },
		clojureFunc = { link = "JackYellow" },
		clojureRepeat = { link = "JackYellow" },
		clojureCharacter = { link = "JackAqua" },
		clojureStringEscape = { link = "JackAqua" },
		clojureException = { link = "JackRed" },
		clojureRegexp = { link = "JackAqua" },
		clojureRegexpEscape = { link = "JackAqua" },
		clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
		clojureRegexpMod = { link = "clojureRegexpCharClass" },
		clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
		clojureParen = { link = "JackFg3" },
		clojureAnonArg = { link = "JackYellow" },
		clojureVariable = { link = "JackBlue" },
		clojureMacro = { link = "JackOrange" },
		clojureMeta = { link = "JackYellow" },
		clojureDeref = { link = "JackYellow" },
		clojureQuote = { link = "JackYellow" },
		clojureUnquote = { link = "JackYellow" },
		cOperator = { link = "JackDarkOrange" },
		cppOperator = { link = "JackDarkOrange" },
		cStructure = { link = "JackOrange" },
		pythonBuiltin = { link = "JackOrange" },
		pythonBuiltinObj = { link = "JackOrange" },
		pythonBuiltinFunc = { link = "JackOrange" },
		pythonFunction = { link = "JackAqua" },
		pythonDecorator = { link = "JackRed" },
		pythonInclude = { link = "JackBlue" },
		pythonImport = { link = "JackBlue" },
		pythonRun = { link = "JackBlue" },
		pythonCoding = { link = "JackBlue" },
		pythonOperator = { link = "JackRed" },
		pythonException = { link = "JackRed" },
		pythonExceptions = { link = "JackDarkOrange" },
		pythonBoolean = { link = "JackDarkOrange" },
		pythonDot = { link = "JackFg3" },
		pythonConditional = { link = "JackRed" },
		pythonRepeat = { link = "JackRed" },
		pythonDottedName = { link = "JackGreenBold" },
		cssBraces = { link = "JackBlue" },
		cssFunctionName = { link = "JackYellow" },
		cssIdentifier = { link = "JackOrange" },
		cssClassName = { link = "JackGreen" },
		cssColor = { link = "JackBlue" },
		cssSelectorOp = { link = "JackBlue" },
		cssSelectorOp2 = { link = "JackBlue" },
		cssImportant = { link = "JackGreen" },
		cssVendor = { link = "JackFg1" },
		cssTextProp = { link = "JackAqua" },
		cssAnimationProp = { link = "JackAqua" },
		cssUIProp = { link = "JackYellow" },
		cssTransformProp = { link = "JackAqua" },
		cssTransitionProp = { link = "JackAqua" },
		cssPrintProp = { link = "JackAqua" },
		cssPositioningProp = { link = "JackYellow" },
		cssBoxProp = { link = "JackAqua" },
		cssFontDescriptorProp = { link = "JackAqua" },
		cssFlexibleBoxProp = { link = "JackAqua" },
		cssBorderOutlineProp = { link = "JackAqua" },
		cssBackgroundProp = { link = "JackAqua" },
		cssMarginProp = { link = "JackAqua" },
		cssListProp = { link = "JackAqua" },
		cssTableProp = { link = "JackAqua" },
		cssFontProp = { link = "JackAqua" },
		cssPaddingProp = { link = "JackAqua" },
		cssDimensionProp = { link = "JackAqua" },
		cssRenderProp = { link = "JackAqua" },
		cssColorProp = { link = "JackAqua" },
		cssGeneratedContentProp = { link = "JackAqua" },
		javaScriptBraces = { link = "JackFg1" },
		javaScriptFunction = { link = "JackAqua" },
		javaScriptIdentifier = { link = "JackRed" },
		javaScriptMember = { link = "JackBlue" },
		javaScriptNumber = { link = "JackDarkOrange" },
		javaScriptNull = { link = "JackDarkOrange" },
		javaScriptParens = { link = "JackFg3" },
		typescriptReserved = { link = "JackAqua" },
		typescriptLabel = { link = "JackAqua" },
		typescriptFuncKeyword = { link = "JackAqua" },
		typescriptIdentifier = { link = "JackOrange" },
		typescriptBraces = { link = "JackFg1" },
		typescriptEndColons = { link = "JackFg1" },
		typescriptDOMObjects = { link = "JackFg1" },
		typescriptAjaxMethods = { link = "JackFg1" },
		typescriptLogicSymbols = { link = "JackFg1" },
		typescriptDocSeeTag = { link = "Comment" },
		typescriptDocParam = { link = "Comment" },
		typescriptDocTags = { link = "vimCommentTitle" },
		typescriptGlobalObjects = { link = "JackFg1" },
		typescriptParens = { link = "JackFg3" },
		typescriptOpSymbols = { link = "JackFg3" },
		typescriptHtmlElemProperties = { link = "JackFg1" },
		typescriptNull = { link = "JackDarkOrange" },
		typescriptInterpolationDelimiter = { link = "JackAqua" },
		purescriptModuleKeyword = { link = "JackAqua" },
		purescriptModuleName = { link = "JackFg1" },
		purescriptWhere = { link = "JackAqua" },
		purescriptDelimiter = { link = "JackFg4" },
		purescriptType = { link = "JackFg1" },
		purescriptImportKeyword = { link = "JackAqua" },
		purescriptHidingKeyword = { link = "JackAqua" },
		purescriptAsKeyword = { link = "JackAqua" },
		purescriptStructure = { link = "JackAqua" },
		purescriptOperator = { link = "JackBlue" },
		purescriptTypeVar = { link = "JackFg1" },
		purescriptConstructor = { link = "JackFg1" },
		purescriptFunction = { link = "JackFg1" },
		purescriptConditional = { link = "JackOrange" },
		purescriptBacktick = { link = "JackOrange" },
		coffeeExtendedOp = { link = "JackFg3" },
		coffeeSpecialOp = { link = "JackFg3" },
		coffeeCurly = { link = "JackOrange" },
		coffeeParen = { link = "JackFg3" },
		coffeeBracket = { link = "JackOrange" },
		rubyStringDelimiter = { link = "JackGreen" },
		rubyInterpolationDelimiter = { link = "JackAqua" },
		rubyDefinedOperator = { link = "rubyKeyword" },
		objcTypeModifier = { link = "JackRed" },
		objcDirective = { link = "JackBlue" },
		goDirective = { link = "JackAqua" },
		goConstants = { link = "JackDarkOrange" },
		goDeclaration = { link = "JackRed" },
		goDeclType = { link = "JackBlue" },
		goBuiltins = { link = "JackOrange" },
		luaIn = { link = "JackRed" },
		luaFunction = { link = "JackAqua" },
		luaTable = { link = "JackOrange" },
		moonSpecialOp = { link = "JackFg3" },
		moonExtendedOp = { link = "JackFg3" },
		moonFunction = { link = "JackFg3" },
		moonObject = { link = "JackYellow" },
		javaAnnotation = { link = "JackBlue" },
		javaDocTags = { link = "JackAqua" },
		javaCommentTitle = { link = "vimCommentTitle" },
		javaParen = { link = "JackFg3" },
		javaParen1 = { link = "JackFg3" },
		javaParen2 = { link = "JackFg3" },
		javaParen3 = { link = "JackFg3" },
		javaParen4 = { link = "JackFg3" },
		javaParen5 = { link = "JackFg3" },
		javaOperator = { link = "JackOrange" },
		javaVarArg = { link = "JackGreen" },
		elixirDocString = { link = "Comment" },
		elixirStringDelimiter = { link = "JackGreen" },
		elixirInterpolationDelimiter = { link = "JackAqua" },
		elixirModuleDeclaration = { link = "JackYellow" },
		scalaNameDefinition = { link = "JackFg1" },
		scalaCaseFollowing = { link = "JackFg1" },
		scalaCapitalWord = { link = "JackFg1" },
		scalaTypeExtension = { link = "JackFg1" },
		scalaKeyword = { link = "JackRed" },
		scalaKeywordModifier = { link = "JackRed" },
		scalaSpecial = { link = "JackAqua" },
		scalaOperator = { link = "JackFg1" },
		scalaTypeDeclaration = { link = "JackYellow" },
		scalaTypeTypePostDeclaration = { link = "JackYellow" },
		scalaInstanceDeclaration = { link = "JackFg1" },
		scalaInterpolation = { link = "JackAqua" },
		markdownItalic = { fg = colors.fg0, italic = true },
		markdownBold = { fg = colors.fg0, bold = true },
		markdownBoldItalic = { fg = colors.fg2, bold = true, italic = true },
		markdownH1 = { link = "JackGreenBold" },
		markdownH2 = { link = "JackGreenBold" },
		markdownH3 = { link = "JackYellowBold" },
		markdownH4 = { link = "JackYellowBold" },
		markdownH5 = { link = "JackYellow" },
		markdownH6 = { link = "JackYellow" },
		markdownCode = { link = "JackAqua" },
		markdownCodeBlock = { link = "JackAqua" },
		markdownCodeDelimiter = { link = "JackAqua" },
		markdownBlockquote = { link = "JackGray" },
		markdownListMarker = { link = "JackGray" },
		markdownOrderedListMarker = { link = "JackGray" },
		markdownRule = { link = "JackGray" },
		markdownHeadingRule = { link = "JackGray" },
		markdownUrlDelimiter = { link = "JackFg3" },
		markdownLinkDelimiter = { link = "JackFg3" },
		markdownLinkTextDelimiter = { link = "JackFg3" },
		markdownHeadingDelimiter = { link = "JackOrange" },
		markdownUrl = { link = "JackGray" },
		markdownUrlTitleDelimiter = { link = "JackGray" },
		markdownLinkText = { fg = colors.gray, underline = config.underline },
		markdownIdDeclaration = { link = "markdownLinkText" },
		haskellType = { link = "JackBlue" },
		haskellIdentifier = { link = "JackAqua" },
		haskellSeparator = { link = "JackFg4" },
		haskellDelimiter = { link = "JackOrange" },
		haskellOperators = { link = "JackDarkOrange" },
		haskellBacktick = { link = "JackOrange" },
		haskellStatement = { link = "JackDarkOrange" },
		haskellConditional = { link = "JackDarkOrange" },
		haskellLet = { link = "JackRed" },
		haskellDefault = { link = "JackRed" },
		haskellWhere = { link = "JackRed" },
		haskellBottom = { link = "JackRedBold" },
		haskellImportKeywords = { link = "JackDarkOrangeBold" },
		haskellDeclKeyword = { link = "JackOrange" },
		haskellDecl = { link = "JackOrange" },
		haskellDeriving = { link = "JackDarkOrange" },
		haskellAssocType = { link = "JackAqua" },
		haskellNumber = { link = "JackAqua" },
		haskellPragma = { link = "JackRedBold" },
		haskellTH = { link = "JackAquaBold" },
		haskellForeignKeywords = { link = "JackGreen" },
		haskellKeyword = { link = "JackRed" },
		haskellFloat = { link = "JackAqua" },
		haskellInfix = { link = "JackDarkOrange" },
		haskellQuote = { link = "JackGreenBold" },
		haskellShebang = { link = "JackYellowBold" },
		haskellLiquid = { link = "JackDarkOrangeBold" },
		haskellQuasiQuoted = { link = "JackBlueBold" },
		haskellRecursiveDo = { link = "JackDarkOrange" },
		haskellQuotedType = { link = "JackRed" },
		haskellPreProc = { link = "JackFg4" },
		haskellTypeRoles = { link = "JackRedBold" },
		haskellTypeForall = { link = "JackRed" },
		haskellPatternKeyword = { link = "JackBlue" },
		jsonKeyword = { link = "JackGreen" },
		jsonQuote = { link = "JackGreen" },
		jsonBraces = { link = "JackFg1" },
		jsonString = { link = "JackFg1" },
		mailQuoted1 = { link = "JackAqua" },
		mailQuoted2 = { link = "JackDarkOrange" },
		mailQuoted3 = { link = "JackYellow" },
		mailQuoted4 = { link = "JackGreen" },
		mailQuoted5 = { link = "JackRed" },
		mailQuoted6 = { link = "JackOrange" },
		mailSignature = { link = "Comment" },
		csBraces = { link = "JackFg1" },
		csEndColon = { link = "JackFg1" },
		csLogicSymbols = { link = "JackFg1" },
		csParens = { link = "JackFg3" },
		csOpSymbols = { link = "JackFg3" },
		csInterpolationDelimiter = { link = "JackFg3" },
		csInterpolationAlignDel = { link = "JackAquaBold" },
		csInterpolationFormat = { link = "JackAqua" },
		csInterpolationFormatDel = { link = "JackAquaBold" },
		rustSigil = { link = "JackOrange" },
		rustEscape = { link = "JackAqua" },
		rustStringContinuation = { link = "JackAqua" },
		rustEnum = { link = "JackAqua" },
		rustStructure = { link = "JackAqua" },
		rustModPathSep = { link = "JackFg2" },
		rustCommentLineDoc = { link = "Comment" },
		rustDefault = { link = "JackAqua" },
		ocamlOperator = { link = "JackFg1" },
		ocamlKeyChar = { link = "JackOrange" },
		ocamlArrow = { link = "JackOrange" },
		ocamlInfixOpKeyword = { link = "JackRed" },
		ocamlConstructor = { link = "JackOrange" },
		LspSagaCodeActionTitle = { link = "Title" },
		LspSagaCodeActionBorder = { link = "JackFg1" },
		LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
		LspSagaLspFinderBorder = { link = "JackFg1" },
		LspSagaAutoPreview = { link = "JackOrange" },
		TargetWord = { fg = colors.light_orange, bold = config.bold },
		FinderSeparator = { link = "JackAqua" },
		LspSagaDefPreviewBorder = { link = "JackBlue" },
		LspSagaHoverBorder = { link = "JackOrange" },
		LspSagaRenameBorder = { link = "JackBlue" },
		LspSagaDiagnosticSource = { link = "JackOrange" },
		LspSagaDiagnosticBorder = { link = "JackDarkOrange" },
		LspSagaDiagnosticHeader = { link = "JackGreen" },
		LspSagaSignatureHelpBorder = { link = "JackGreen" },
		SagaShadow = { link = "JackBg0" },
		DashboardShortCut = { link = "JackOrange" },
		DashboardHeader = { link = "JackAqua" },
		DashboardCenter = { link = "JackYellow" },
		DashboardFooter = { fg = colors.purple, italic = true },
		MasonHighlight = { link = "JackAqua" },
		MasonHighlightBlock = { fg = colors.bg0, bg = colors.light_orange },
		MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.light_orange, bold = true },
		MasonHighlightSecondary = { fg = colors.yellow },
		MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
		MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
		MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
		MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
		MasonMuted = { fg = colors.fg4 },
		MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
		MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
		LspInlayHint = { link = "comment" },
		CarbonFile = { link = "JackFg1" },
		CarbonExe = { link = "JackYellow" },
		CarbonSymlink = { link = "JackAqua" },
		CarbonBrokenSymlink = { link = "JackRed" },
		CarbonIndicator = { link = "JackGray" },
		CarbonDanger = { link = "JackRed" },
		CarbonPending = { link = "JackYellow" },
		NoiceCursor = { link = "TermCursor" },
		NoiceCmdlinePopupBorder = { fg = colors.light_orange, bg = nil },
		NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
		NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
		NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
		NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
		NotifyDEBUGBorder = { link = "JackBlue" },
		NotifyDEBUGIcon = { link = "JackBlue" },
		NotifyDEBUGTitle = { link = "JackBlue" },
		NotifyERRORBorder = { link = "JackRed" },
		NotifyERRORIcon = { link = "JackRed" },
		NotifyERRORTitle = { link = "JackRed" },
		NotifyINFOBorder = { link = "JackAqua" },
		NotifyINFOIcon = { link = "JackAqua" },
		NotifyINFOTitle = { link = "JackAqua" },
		NotifyTRACEBorder = { link = "JackGreen" },
		NotifyTRACEIcon = { link = "JackGreen" },
		NotifyTRACETitle = { link = "JackGreen" },
		NotifyWARNBorder = { link = "JackYellow" },
		NotifyWARNIcon = { link = "JackYellow" },
		NotifyWARNTitle = { link = "JackYellow" },
		IlluminatedWordText = { link = "LspReferenceText" },
		IlluminatedWordRead = { link = "LspReferenceRead" },
		IlluminatedWordWrite = { link = "LspReferenceWrite" },
		TSRainbowRed = { fg = colors.red },
		TSRainbowOrange = { fg = colors.orange },
		TSRainbowYellow = { fg = colors.yellow },
		TSRainbowGreen = { fg = colors.green },
		TSRainbowBlue = { fg = colors.light_orange },
		TSRainbowViolet = { fg = colors.purple },
		TSRainbowCyan = { fg = colors.aqua },
		RainbowDelimiterRed = { fg = colors.red },
		RainbowDelimiterOrange = { fg = colors.orange },
		RainbowDelimiterYellow = { fg = colors.yellow },
		RainbowDelimiterGreen = { fg = colors.green },
		RainbowDelimiterBlue = { fg = colors.light_orange },
		RainbowDelimiterViolet = { fg = colors.purple },
		RainbowDelimiterCyan = { fg = colors.aqua },
		DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
		DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
		DapUIBreakpointsCurrentLine = { link = "JackYellow" },
		DapUIBreakpointsDisabledLine = { link = "JackGray" },
		DapUIBreakpointsInfo = { link = "JackAqua" },
		DapUIBreakpointsLine = { link = "JackYellow" },
		DapUIBreakpointsPath = { link = "JackBlue" },
		DapUICurrentFrameName = { link = "JackDarkOrange" },
		DapUIDecoration = { link = "JackDarkOrange" },
		DapUIEndofBuffer = { link = "EndOfBuffer" },
		DapUIFloatBorder = { link = "JackAqua" },
		DapUILineNumber = { link = "JackYellow" },
		DapUIModifiedValue = { link = "JackRed" },
		DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
		DapUIRestart = { fg = colors.green, bg = colors.bg1 },
		DapUIScope = { link = "JackBlue" },
		DapUISource = { link = "JackFg1" },
		DapUIStepBack = { fg = colors.light_orange, bg = colors.bg1 },
		DapUIStepInto = { fg = colors.light_orange, bg = colors.bg1 },
		DapUIStepOut = { fg = colors.light_orange, bg = colors.bg1 },
		DapUIStepOver = { fg = colors.light_orange, bg = colors.bg1 },
		DapUIStop = { fg = colors.red, bg = colors.bg1 },
		DapUIStoppedThread = { link = "JackBlue" },
		DapUIThread = { link = "JackBlue" },
		DapUIType = { link = "JackOrange" },
		DapUIUnavailable = { link = "JackGray" },
		DapUIWatchesEmpty = { link = "JackGray" },
		DapUIWatchesError = { link = "JackRed" },
		DapUIWatchesValue = { link = "JackYellow" },
		DapUIWinSelect = { link = "JackYellow" },
		NeogitDiffDelete = { link = "DiffDelete" },
		NeogitDiffAdd = { link = "DiffAdd" },
		NeogitHunkHeader = { link = "WinBar" },
		NeogitHunkHeaderHighlight = { link = "WinBarNC" },
		DiffviewStatusModified = { link = "JackGreenBold" },
		DiffviewFilePanelInsertions = { link = "JackGreenBold" },
		DiffviewFilePanelDeletions = { link = "JackRedBold" },
		MiniAnimateCursor = { reverse = true, nocombine = true },
		MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
		MiniClueBorder = { link = "FloatBorder" },
		MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
		MiniClueDescSingle = { link = "NormalFloat" },
		MiniClueNextKey = { link = "DiagnosticFloatingHint" },
		MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
		MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
		MiniClueTitle = { link = "FloatTitle" },
		MiniCompletionActiveParameter = { underline = true },
		MiniCursorword = { underline = true },
		MiniCursorwordCurrent = { underline = true },
		MiniDepsChangeAdded = { link = "JackGreen" },
		MiniDepsChangeRemoved = { link = "JackRed" },
		MiniDepsHint = { link = "DiagnosticHint" },
		MiniDepsInfo = { link = "DiagnosticInfo" },
		MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
		MiniDepsPlaceholder = { link = "Comment" },
		MiniDepsTitle = { link = "Title" },
		MiniDepsTitleError = { link = "DiffDelete" },
		MiniDepsTitleSame = { link = "DiffChange" },
		MiniDepsTitleUpdate = { link = "DiffAdd" },
		MiniDiffOverAdd = { link = "DiffAdd" },
		MiniDiffOverChange = { link = "DiffText" },
		MiniDiffOverContext = { link = "DiffChange" },
		MiniDiffOverDelete = { link = "DiffDelete" },
		MiniDiffSignAdd = { link = "JackGreen" },
		MiniDiffSignChange = { link = "JackAqua" },
		MiniDiffSignDelete = { link = "JackRed" },
		MiniFilesBorder = { link = "FloatBorder" },
		MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
		MiniFilesCursorLine = { bg = colors.bg2 },
		MiniFilesDirectory = { link = "Directory" },
		MiniFilesFile = { link = "JackFg1" },
		MiniFilesNormal = { link = "NormalFloat" },
		MiniFilesTitle = { link = "FloatTitle" },
		MiniFilesTitleFocused = { link = "JackOrangeBold" },
		MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
		MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
		MiniHipatternsNote = { fg = colors.bg0, bg = colors.light_orange, bold = config.bold },
		MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
		MiniIconsAzure = { link = "JackBlue" },
		MiniIconsBlue = { link = "JackBlue" },
		MiniIconsCyan = { link = "JackAqua" },
		MiniIconsGreen = { link = "JackGreen" },
		MiniIconsGrey = { link = "JackFg0" },
		MiniIconsOrange = { link = "JackOrange" },
		MiniIconsPurple = { link = "JackDarkOrange" },
		MiniIconsRed = { link = "JackRed" },
		MiniIconsYellow = { link = "JackYellow" },
		MiniIndentscopeSymbol = { link = "JackGray" },
		MiniIndentscopeSymbolOff = { link = "JackYellow" },
		MiniJump = { link = "JackOrangeUnderline" },
		MiniJump2dDim = { link = "JackGray" },
		MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
		MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
		MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
		MiniMapNormal = { link = "NormalFloat" },
		MiniMapSymbolCount = { link = "Special" },
		MiniMapSymbolLine = { link = "Title" },
		MiniMapSymbolView = { link = "Delimiter" },
		MiniNotifyBorder = { link = "FloatBorder" },
		MiniNotifyNormal = { link = "NormalFloat" },
		MiniNotifyTitle = { link = "FloatTitle" },
		MiniOperatorsExchangeFrom = { link = "IncSearch" },
		MiniPickBorder = { link = "FloatBorder" },
		MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
		MiniPickBorderText = { link = "FloatTitle" },
		MiniPickIconDirectory = { link = "Directory" },
		MiniPickIconFile = { link = "MiniPickNormal" },
		MiniPickHeader = { link = "DiagnosticFloatingHint" },
		MiniPickMatchCurrent = { bg = colors.bg2 },
		MiniPickMatchMarked = { link = "Visual" },
		MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
		MiniPickNormal = { link = "NormalFloat" },
		MiniPickPreviewLine = { link = "CursorLine" },
		MiniPickPreviewRegion = { link = "IncSearch" },
		MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
		MiniStarterCurrent = { nocombine = true },
		MiniStarterFooter = { link = "JackGray" },
		MiniStarterHeader = { link = "Title" },
		MiniStarterInactive = { link = "Comment" },
		MiniStarterItem = { link = "Normal" },
		MiniStarterItemBullet = { link = "Delimiter" },
		MiniStarterItemPrefix = { link = "WarningMsg" },
		MiniStarterSection = { link = "Delimiter" },
		MiniStarterQuery = { link = "MoreMsg" },
		MiniStatuslineDevinfo = { link = "StatusLine" },
		MiniStatuslineFileinfo = { link = "StatusLine" },
		MiniStatuslineFilename = { link = "StatusLineNC" },
		MiniStatuslineInactive = { link = "StatusLineNC" },
		MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, nocombine = true },
		MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.light_orange, bold = config.bold, nocombine = true },
		MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold, nocombine = true },
		MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold, nocombine = true },
		MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold, nocombine = true },
		MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold, nocombine = true },
		MiniSurround = { link = "IncSearch" },
		MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
		MiniTablineFill = { link = "TabLineFill" },
		MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
		MiniTablineModifiedCurrent = {
			fg = colors.bg1,
			bg = colors.green,
			bold = config.bold,
			reverse = config.invert_tabline,
		},
		MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
		MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
		MiniTablineTabpagesection = { link = "Search" },
		MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
		MiniTestEmphasis = { bold = config.bold },
		MiniTestFail = { link = "JackRedBold" },
		MiniTestPass = { link = "JackGreenBold" },
		MiniTrailspace = { bg = colors.red },
		["@comment"] = { link = "Comment" },
		["@none"] = { bg = "NONE", fg = "NONE" },
		["@preproc"] = { link = "PreProc" },
		["@define"] = { link = "Define" },
		["@operator"] = { link = "Operator" },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.bracket"] = { link = "Delimiter" },
		["@punctuation.special"] = { link = "Delimiter" },
		["@string"] = { link = "String" },
		["@string.regex"] = { link = "String" },
		["@string.regexp"] = { link = "String" },
		["@string.escape"] = { link = "SpecialChar" },
		["@string.special"] = { link = "SpecialChar" },
		["@string.special.path"] = { link = "Underlined" },
		["@string.special.symbol"] = { link = "Identifier" },
		["@string.special.url"] = { link = "Underlined" },
		["@character"] = { link = "Character" },
		["@character.special"] = { link = "SpecialChar" },
		["@boolean"] = { link = "Boolean" },
		["@number"] = { link = "Number" },
		["@number.float"] = { link = "Float" },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Special" },
		["@function.call"] = { link = "Function" },
		["@function.macro"] = { link = "Macro" },
		["@function.method"] = { link = "Function" },
		["@method"] = { link = "Function" },
		["@method.call"] = { link = "Function" },
		["@constructor"] = { link = "Special" },
		["@parameter"] = { link = "Identifier" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.debug"] = { link = "Debug" },
		["@keyword.directive"] = { link = "PreProc" },
		["@keyword.directive.define"] = { link = "Define" },
		["@keyword.exception"] = { link = "Exception" },
		["@keyword.function"] = { link = "Keyword" },
		["@keyword.import"] = { link = "Include" },
		["@keyword.operator"] = { link = "JackRed" },
		["@keyword.repeat"] = { link = "Repeat" },
		["@keyword.return"] = { link = "Keyword" },
		["@keyword.storage"] = { link = "StorageClass" },
		["@conditional"] = { link = "Conditional" },
		["@repeat"] = { link = "Repeat" },
		["@debug"] = { link = "Debug" },
		["@label"] = { link = "Label" },
		["@include"] = { link = "Include" },
		["@exception"] = { link = "Exception" },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "Type" },
		["@type.definition"] = { link = "Typedef" },
		["@type.qualifier"] = { link = "Type" },
		["@storageclass"] = { link = "StorageClass" },
		["@attribute"] = { link = "PreProc" },
		["@field"] = { link = "Identifier" },
		["@property"] = { link = "Identifier" },
		["@variable"] = { link = "JackFg1" },
		["@variable.builtin"] = { link = "Special" },
		["@variable.member"] = { link = "Identifier" },
		["@variable.parameter"] = { link = "Identifier" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Special" },
		["@constant.macro"] = { link = "Define" },
		["@markup"] = { link = "JackFg1" },
		["@markup.strong"] = { bold = config.bold },
		["@markup.italic"] = { link = "@text.emphasis" },
		["@markup.underline"] = { underline = config.underline },
		-- ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
		["@markup.heading"] = { link = "Title" },
		["@markup.raw"] = { link = "String" },
		["@markup.math"] = { link = "Special" },
		["@markup.environment"] = { link = "Macro" },
		["@markup.environment.name"] = { link = "Type" },
		["@markup.link"] = { link = "Underlined" },
		["@markup.link.label"] = { link = "SpecialChar" },
		["@markup.list"] = { link = "Delimiter" },
		["@markup.list.checked"] = { link = "JackGreen" },
		["@markup.list.unchecked"] = { link = "JackGray" },
		["@comment.todo"] = { link = "Todo" },
		["@comment.note"] = { link = "SpecialComment" },
		["@comment.warning"] = { link = "WarningMsg" },
		["@comment.error"] = { link = "ErrorMsg" },
		["@diff.plus"] = { link = "diffAdded" },
		["@diff.minus"] = { link = "diffRemoved" },
		["@diff.delta"] = { link = "diffChanged" },
		["@module"] = { link = "JackFg1" },
		["@namespace"] = { link = "JackFg1" },
		["@symbol"] = { link = "Identifier" },
		["@text"] = { link = "JackFg1" },
		["@text.strong"] = { bold = config.bold },
		["@text.emphasis"] = { italic = config.italic_emphasis },
		["@text.underline"] = { underline = config.underline },
		["@text.strike"] = { strikethrough = config.strikethrough },
		["@text.title"] = { link = "Title" },
		["@text.literal"] = { link = "String" },
		["@text.uri"] = { link = "Underlined" },
		["@text.math"] = { link = "Special" },
		["@text.environment"] = { link = "Macro" },
		["@text.environment.name"] = { link = "Type" },
		["@text.reference"] = { link = "Constant" },
		["@text.todo"] = { link = "Todo" },
		["@text.todo.checked"] = { link = "JackGreen" },
		["@text.todo.unchecked"] = { link = "JackGray" },
		["@text.note"] = { link = "SpecialComment" },
		["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
		["@text.warning"] = { link = "WarningMsg" },
		["@text.danger"] = { link = "ErrorMsg" },
		["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
		["@text.diff.add"] = { link = "diffAdded" },
		["@text.diff.delete"] = { link = "diffRemoved" },
		["@tag"] = { link = "Tag" },
		["@tag.attribute"] = { link = "Identifier" },
		["@tag.delimiter"] = { link = "Delimiter" },
		["@punctuation"] = { link = "Delimiter" },
		["@macro"] = { link = "Macro" },
		["@structure"] = { link = "Structure" },
		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@macro" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@constant" },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.interface"] = { link = "@constructor" },
		["@lsp.type.macro"] = { link = "@macro" },
		["@lsp.type.method"] = { link = "@method" },
		["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.struct"] = { link = "@type" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.typeParameter"] = { link = "@type.definition" },
		["@lsp.type.variable"] = { link = "@variable" },
	}

	for group, hl in pairs(config.overwrites) do
		if groups[group] then
			groups[group].link = nil
		end
		groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
	end
	return groups
end

--- @param opts table<Theme>
Jack.load = function(opts)
	if vim.version().minor < 8 then
		vim.notify_once("jack.nvim: requires neovim version 0.8 or higher")
		return
	end

	local theme = opts["_theme"]
	if vim.g.colors_name then
		vim.cmd.hi("clear")
	end

	local groups = nil
	if theme ~= nil and theme == "tiger" then
		vim.g.colors_name = "jack-tiger"
		vim.o.termguicolors = true
		groups = Tiger.get_groups()
	end

	if groups == nil then
		vim.notify_once("jack.nvim: could not retrive groups")
		return
	end
	for group, settings in pairs(groups) do
		vim.api.nvim_set_hl(0, group, settings)
	end
end

return Jack
